# Generated by Django 4.1.3 on 2022-11-25 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=15)),
                ('preco', models.FloatField()),
                ('data_cadastro', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('alugado', models.BooleanField(blank=True, default=False)),
                ('nome_alugado', models.CharField(blank=True, max_length=30, null=True)),
                ('data_alugado', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('tempo_aluguel', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
