# Generated by Django 4.1.3 on 2022-11-28 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('carros', '0003_categoria_carro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
