# Generated by Django 4.1.3 on 2022-12-11 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_alter_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='avalicao',
            field=models.CharField(blank=True, choices=[('P', 'Péssimo'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 14, 57, 39, 295757)),
        ),
    ]
