# Generated by Django 4.1.3 on 2022-12-11 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0010_alter_emprestimo_avalicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 14, 57, 49, 21576)),
        ),
    ]
