# Generated by Django 4.1.3 on 2022-12-11 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0013_alter_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 18, 36, 2, 202846)),
        ),
    ]
