# Generated by Django 4.1.3 on 2022-12-11 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0015_alter_carro_alugado_alter_emprestimo_avalicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 20, 14, 30, 29195)),
        ),
    ]
