# Generated by Django 4.1.3 on 2022-12-12 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0016_alter_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='alugado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 13, 35, 17, 941288)),
        ),
    ]
