# Generated by Django 4.1.3 on 2022-12-12 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0017_alter_carro_alugado_alter_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 14, 28, 59, 165197)),
        ),
    ]
