# Generated by Django 4.1.3 on 2022-12-12 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0022_alter_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='avalicao',
            new_name='avaliacao',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 17, 51, 8, 737804)),
        ),
    ]
