# Generated by Django 4.1.3 on 2022-12-12 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0028_alter_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('Péssimo', 'Péssimo'), ('Bom', 'Bom'), ('Ótimo', 'Ótimo')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 20, 38, 59, 143814)),
        ),
    ]
