# Generated by Django 4.1.3 on 2022-12-12 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0029_alter_emprestimo_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_carros'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 20, 46, 9, 431269)),
        ),
    ]
