# Generated by Django 4.1.3 on 2022-12-13 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0030_carro_img_alter_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='img',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 23, 18, 58, 664331)),
        ),
    ]
